server:
  port: 8081
  
#You need a message broker that’s ready to relay those messages between producers and consumers.
#By default, Spring assumes that your Artemis broker is listening on localhost at port 61616. 
#That’s fine for development purposes, but once you’re ready to send your application into production, 
#you’ll need to set a few properties that tell Spring how to access the broker.
#This sets up Spring to create broker connections to an Artemis broker listening at artemis.tacocloud.com, port 61617
#The credentials are optional, but they’re recommended for production deployments
#The values given here are actually the default values. But they are explicitly set here as an example of setting the Artemis properties.
Spring:
  jms:
    template:
      receive-timeout: 2
  artemis:
    host: localhost
    port: 61616
    user: tacoweb
    password: letm31n
    embedded:
      enabled: false
#  profiles:
#    active:
#      - rabbitmq-template
      
---
spring:
  profiles: rabbitmq-template
    
  rabbitmq:
    template:
      receive-timeout: 30000